import axios, { AxiosError } from 'axios';
import { BaseAIProvider } from './AIProvider.js';
import { PromptContext } from '../types/index.js';

/**
 * Google Gemini Pro AI provider implementation
 * Uses Google's Gemini Pro model for premium quality code generation
 */
export class GeminiProProvider extends BaseAIProvider {
  name = 'gemini-pro';
  private apiKey: string;
  private baseURL = 'https://generativelanguage.googleapis.com/v1beta';
  private model = 'gemini-2.5-flash'; // Fast model (Pro tier uses same as free but with higher limits)

  constructor(apiKey: string) {
    super();
    this.apiKey = apiKey;
    console.log('Gemini Pro Provider initialized with API key:', apiKey ? `${apiKey.substring(0, 10)}...` : 'MISSING');
  }

  async generate(prompt: string, context: PromptContext): Promise<string> {
    try {
      const systemPrompt = this.buildSystemPrompt(context);
      
      // Combine system prompt and user prompt for Gemini
      const fullPrompt = `${systemPrompt}\n\nUser Request:\n${prompt}`;
      
      const response = await axios.post(
        `${this.baseURL}/models/${this.model}:generateContent?key=${this.apiKey}`,
        {
          contents: [{
            parts: [{
              text: fullPrompt
            }]
          }],
          generationConfig: {
            temperature: 0.8, // Higher for more creative, advanced solutions
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 16384, // Maximum for complex, enterprise-grade plugins
          },
          safetySettings: [
            {
              category: 'HARM_CATEGORY_HARASSMENT',
              threshold: 'BLOCK_NONE'
            },
            {
              category: 'HARM_CATEGORY_HATE_SPEECH',
              threshold: 'BLOCK_NONE'
            },
            {
              category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
              threshold: 'BLOCK_NONE'
            },
            {
              category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
              threshold: 'BLOCK_NONE'
            }
          ]
        },
        {
          headers: {
            'Content-Type': 'application/json'
          },
          timeout: 90000 // Maximum timeout for enterprise-grade plugins
        }
      );

      // Extract text from Gemini response
      const generatedText = response.data.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (!generatedText) {
        throw new Error('No content generated by Gemini Pro');
      }

      return this.extractCode(generatedText);
    } catch (error) {
      if (axios.isAxiosError(error)) {
        const axiosError = error as AxiosError;
        console.error('Gemini Pro API Error Details:', {
          status: axiosError.response?.status,
          statusText: axiosError.response?.statusText,
          data: JSON.stringify(axiosError.response?.data),
          code: axiosError.code
        });
        
        if (axiosError.response?.status === 429) {
          throw new Error('Rate limit exceeded');
        }
        if (axiosError.response?.status === 400) {
          throw new Error('Invalid request to Gemini Pro API');
        }
        if (axiosError.response?.status === 403) {
          throw new Error('Invalid API key or API not enabled');
        }
        if (axiosError.code === 'ECONNABORTED') {
          throw new Error('Request timeout');
        }
      }
      throw new Error(`Gemini Pro API error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  async isAvailable(): Promise<boolean> {
    try {
      // Test with a simple request
      await axios.get(
        `${this.baseURL}/models/${this.model}?key=${this.apiKey}`,
        { timeout: 5000 }
      );
      return true;
    } catch {
      return false;
    }
  }

  private buildSystemPrompt(context: PromptContext): string {
    return context.additionalContext;
  }
}
